# 45장. 프로미스

## 목차

- [45.1 비동기 처리를 위한 콜백 패턴의 단점](#451-비동기-처리를-위한-콜백-패턴의-단점)
  * [45.1.1 콜백 헬](#4511-콜백-헬)
  * [45.1.2 에러 처리의 한계](#4512-에러-처리의-한계)
- [45.2 프로미스의 생성](#452-프로미스의-생성)
- [45.3 프로미스의 후속 처리 메서드](#453-프로미스의-후속-처리-메서드)
  * [45.3.1 Promise.prototype.then](#4531-promiseprototypethen)
  * [45.3.2 Promise.prototype.catch](#4532-promiseprototypecatch)
  * [45.3.3 Promise.prototype.finally](#4533-promiseprototypefinally)
- [45.4 프로미스의 에러 처리](#454-프로미스의-에러-처리)
- [45.5 프로미스 체이닝](#455-프로미스-체이닝)
- [45.6 프로미스의 정적 메서드](#456-프로미스의-정적-메서드)
  * [45.6.1 Promise.resolve / Promise.reject](#4561-promiseresolve--promisereject)
  * [45.6.2 Promise.all](#4562-promiseall)
  * [45.6.3 Promise.race](#4563-promiserace)
  * [45.6.4 Promise.allsettled](#4564-promiseallsettled)
- [45.7 마이크로태스크 큐](#457-마이크로태스크-큐)
- [45.8 fetch](#458-fetch)
  * [Response의 json 객체](#response의-json-객체)
  * [fetch의 에러](#fetch의-에러)
  * [GET](#get)
  * [POST](#post)
  * [PATCH](#patch)
  * [DELETE](#delete)

---

전통적인 콜백 패턴의 단점인 콜백 헬과, 에러 처리의 곤란, 여러 개의 비동기 처리의 한계를 개선하기 위해 도입되었다.

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

비동기 함수를 호출하면, 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다.

즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.

> `setTimeout` 함수를 호출하면, 콜백 함수를 호출 스케줄링한 다음, 타이머 id를 반환하고 즉시 종료된다.
> 

```jsx
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

	// onload 이벤트 핸들러는 비동기로 동작한다.
  xhr.onload = () => {
    if (xhr.status === 200) {
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere ...",
  "body": "quia et suscipit ..."
}
*/
```

다음 get 함수를 호출하면, XMLHttpRequest 객체를 생성하고, HTTP 요청을 초기화한 후, HTTP 요청을 전송한다.

그리고 `xhr.onload` 이벤트 핸들러 프로퍼티에 **이벤트 핸들러를 바인딩**하고 종료한다.

`xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 **get 함수의 반환문이 아니다.**

- `onload` 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 캐치가 불가능하고, **이벤트 핸들러에서의 반환은 의미가 없다**.
- `onload` 함수 내부에서 서버의 응답을 상위 스코프의 변수에 할당하면 **처리 순서가 보장되지 않는다**.
- 서버로부터 응답이 도착하고, xhr 객체에서 load 이벤트가 발생되도 `onload` 핸들러 프로퍼티에 바인딩한 **이벤트 핸들러가 즉시 실행되지 않는다**.
    - 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

<aside>

💡 비동기 함수는 **비동기 처리 결과**를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.
비동기 함수의 처리 결과에 대한 후속 처리는 **비동기 함수 내부에서 수행**해야 한다.
- 후속 처리를 수행할 콜백 함수 전달이 일반적이다.

</aside>

비동기 처리 결과를 가지고 또 다시 비동기 함수를 호출해야 된다면 콜백 함수 호출이 중첩된다.

콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상을 **콜백 헬** 이라고 한다.

```jsx
get('/step1', a => {
  get(`/step2/${a}`, b => {
    get(`/step3/${b}`, c => {
      get(`/step4/${c}`, d => {
        console.log(d);
      });
    });
  });
});
```

### 45.1.2 에러 처리의 한계

```jsx
try {
  setTimeout(() => { throw new Error('Error!'); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error('캐치한 에러', e);
}
```

다음 코드에서 발생한 에러는 `catch` 코드 블록에서 캐치되지 않는다.

1. `setTimeout`이 호출되면, 함수 실행 컨텍스트가 생성되어 **콜 스택**에 **푸시**되어 실행된다.
2. 비동기 함수이기 때문에 콜백 함수의 호출을 기다리지 않고 즉시 종료되어 **콜 스택**에서 **제거**된다.
3. 타이머가 만료되면 콜백 함수는 **태스크 큐**로 **푸시**된다.
4. 콜 스택이 비어있을 때, 콜백 함수는 **이벤트 루프**에 의해 **콜 스택**으로 **푸시**되어 실행된다.

이 상황에서, 콜백 함수를 호출한 것은 `setTimeout`이 아니다.

<aside>

💡 에러는 **호출자 방향**으로 전파된다. 즉, 콜 스택의 아래 방향으로 전파된다.

</aside>

따라서, `setTimeout`의 콜백 함수가 발생시킨 에러는 `catch` 블록에서 캐치되지 않는다.

## 45.2 프로미스의 생성

ES6에서 도입된 `Promise`는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체다.

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인자로 전달받고,
이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

- `resolve` 인자: 비동기 처리 결과(성공)
- `reject` 인자: 에러(실패)

프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.

| 프로미스의 상태 정보 | 의미 | 상태 변경 조건 |
| --- | --- | --- |
| `pending` | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| `fulfilled` | 비동기 처리가 수행된 상태 (성공) | resolve 함수 호출 |
| `rejected`  | 비동기 처리가 수행된 상태 (실패) | rejcet 함수 호출 |

프로미스의 상태는 `resolve` 또는 `rejcect` 함수를 호출하는 것으로 결정된다.

`pending`이 아닌, 비동기 처리가 수행된 `fulfilled` 또는 `rejected` 상태를 `settled` 상태라고 한다.

`settled` 상태가 되면 더는 다른 상태로 변화할 수 없다.

프로미스는 비동기 처리 상태(`PromiseStatus`)와 더불어 **비동기 처리 결과**(**`PromiseValue`**)도 상태로 가지고 있다.

## 45.3 프로미스의 후속 처리 메서드

비동기 처리 상태의 변화에 따른 후속 처리를 위해 `then`, `catch`, `finally`를 제공한다.

프로미스의 비동기 처리 상태가 변화하면, 후속 처리 메서드에 인수로 전달한 콜백 함수가 **선택적으로 호출**된다.

### 45.3.1 Promise.prototype.then

`then` 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

이 때, 첫 번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 콜백 함수이며, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 콜백 함수이다.

```jsx
// fulfilled
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

`then` 메서드는 언제나 **프로미스**를 반환한다.

### 45.3.2 Promise.prototype.catch

`catch` 메서드는 한 개의 콜백 함수를 인수로 전달받으며, 프로미스가 `rejected` 상태인 경우만 호출된다.

`catch` 메서드는 내부적으로 `then(undefined, onRejected)`를 호출하기에 이와 동일하게 동작한다.
따라서 언제나 프로미스를 반환한다.

```jsx
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.log(e)); // Error: rejected
```

### 45.3.3 Promise.prototype.finally

`finally` 메서드는 한 개의 콜백 함수를 인수로 전달받으며, 프로미스의 성공/실패와 상관 없이 무조건 한 번 호출된다.

`finally` 메서드 역시 언제나 프로미스를 반환한다.

```jsx
new Promise(() => {})
  .finally(() => console.log('finally')); // finally
```

## 45.4 프로미스의 에러 처리

`then`, `catch`, `finally`를 사용하여 처리한다.

다만, `then`의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 복잡해지기 때문에 `catch`를 권장한다.

```jsx
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(err => console.error(err)); // Error: 404
```

## 45.5 프로미스 체이닝

```jsx
const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err));
```

`then`, `catch`, `finally` 후속 처리 메서드는 언제나 프로미스를 반환하기 때문에 연속적으로 호출할 수 있다.

이를 프로미스 체이닝이라고 한다.

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 콜백 헬이 발생하지 않는다.

다만, 콜백함수를 사용하는데, 이 콜백 함수의 가독성이 좋지 않다.

이는 ES6의 `async`/`await`을 통해 해결할 수 있다.

## 45.6 프로미스의 정적 메서드

`Promise` 는 주로 생성자 함수로 사용되지만, **함수도 객체**이기 때문에 메서드를 가질 수 있다.

### 45.6.1 Promise.resolve / Promise.reject

이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

인수로 전달받은 값을 `resolve`/`reject`하는 프로미스를 생성한다.

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]
```

### 45.6.2 Promise.all

여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```jsx
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error);
```

`Promise.all`은 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 인수로 받은 이터러블의 요소가 프로미스가 아닌 경우, `Promise.resolve` 를 통해 프로미스로 래핑한다.

전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 이 때, 첫 번째 프로미스가 가장 나중에 `fulfilled` 상태가 되어도 첫 번째 프로미스보다 차례대로 배열에 저장하기 때문에 **처리 순서가 보장**된다.

인수로 전달받은 배열의 프로미스가 하나라도 `reject` 상태가 되면 **즉시 종료**한다.

### 45.6.3 Promise.race

`Promise.race`는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받아 가장 **먼저** `fulfilled` 상태가 된 프로미스의 처리 결과를 `resolve`하는 새로운 프로미스를 반환한다.

```jsx
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000)) // 3
])
  .then(console.log) // 3
  .catch(console.log);
```

프로미스가 하나라도 `rejected` 상태가 되면, 에러를 `reject`하는 새로운 프로미스를 즉시 반환한다.

### 45.6.4 Promise.allsettled

프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받아 모든 프로미스가 모두 `settled` 상태가 되면 처리 결과를 배열로 반환한다.

```jsx
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000))
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

프로미스의 처리 결과를 나타내는 객체는 다음과 같은 값을 갖는다.

- **`fulfilled`**
    - `status`
    - `value`
- **`rejected`**
    - `status`
    - `reason`

## 45.7 마이크로태스크 큐

프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 **마이크로태스트 큐에** 저장된다.

- **마이크로태스크 큐**
    - 프로미스의 후속 처리 메서드의 콜백 함수 임시 저장
- **태스크 큐**
    - 비동기 함수의 콜백 함수 임시 저장
    - 이벤트 핸들러 임시 저장

마이크로태스크 큐는 태스크 큐와 거의 비슷하지만, **마이크로태스크 큐**가 **우선순위가 높다**는 점이 다르다.

즉, 콜 스택이 비면 이벤트 루프는 먼저 마이크로태스크 큐를 확인한다.

## 45.8 fetch

`fetch`는 `XMLHttpRequest` 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이트 Web API다.

`fetch` 함수는 URL, HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 인자로 하여 HTTP 응답을 나타내는 Response 객체를 래핑한 `Promise` 객체를 반환한다. 그렇기에 `then`을 통해 프로미스가 `resolve`한 Response 객체를 전달받을 수 있다.

### Response의 json 객체

`Response.prototype.json`을 통해 얻을 수 있다.

```jsx
fetch('https://jsonplaceholder.typicode.com/todos/1')
  // response는 HTTP 응답을 나타내는 Response 객체이다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then(response => response.json())
  // json은 역직렬화된 HTTP 응답 몸체이다.
  .then(json => console.log(json));
  // {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

### fetch의 에러

`404 Not Found`와 같은 HTTP 에러는 `reject`하지 않고, `ok`를 `false`로 한 Response 객체를 `resolve`한다.

즉, 오프라인 등의 **네트워크 장애**나 **CORS 에러**에 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject`한다. 따라서 `resove`한 객체의 `ok`를 확인하여 명시적으로 에러 처리를 할 필요가 있다.

> 참고) Axios는 모든 HTTP 에러를 reject 하는 프로미스를 반환한다.
> 

### GET

```jsx
request.get('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

### POST

```jsx
request.post('https://jsonplaceholder.typicode.com/todos', {
  userId: 1,
  title: 'JavaScript',
  completed: false
}).then(response => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, title: "JavaScript", completed: false, id: 201}
```

### PATCH

```jsx
request.patch('https://jsonplaceholder.typicode.com/todos/1', {
  completed: true
}).then(response => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: true}
```

### DELETE

```jsx
request.delete('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then(todos => console.log(todos))
  .catch(err => console.error(err));
// {}
```